[build]
  node_bundler = "esbuild"
  functions = "backend"
  publish = "frontend/build"
  command = "npm install && npm run build"

[dev]
  functions = "backend"
  publish = "dist"
  node_bundler = "esbuild"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
