[build]
  node_bundler = "esbuild"
  functions = "backend/functions"
  publish = "frontend/build"
  included_files = ["backend/models/**"]
  command = "npm install && npm run build"

[dev]
  node_bundler = "esbuild"
  functions = "backend/functions"
  publish = "dist"
  included_files = ["backend/models/**"]
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
